services:
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        ports:
            - '5000:5000'
        environment:
            - MONGO_URI=mongodb+srv://Per-ulv:0CqEsI4xXHoWNcMM@job-app.i3by3uc.mongodb.net/Job-Search?retryWrites=true&w=majority&appName=Job-App
            - SECRET_KEY=vQeVBdddo1Ybiin
            - PORT=5000
        image: server-image
        env_file:
            - ./server/.env
        volumes:
            - ./server:/app/server
        command: npm run start

    client:
        build:
            context: .
            dockerfile: ./client/Dockerfile
        ports:
            - '80:80'
        environment:
            - REACT_APP_API_URL=http://server:5000
        image: client-image
        depends_on:
            - server
